### ISSUE TITLE
White back ground in visualizer

### ISSUE THREAD

**Issue by ERGOWHO** [idiap/ESLAM#10]
![image](https://github.com/idiap/ESLAM/assets/69840908/907697b0-eb5b-4233-9467-2a967e30ed18)

I do not have any errors or working in the previews steps, but after I run python visualizer.py configs/Replica/room0.yaml --output output/Replica/room0 --top_view --save_rendering

I only got this red line and green line moving video, the background, which is supposed to be the room0, is just white color.

Is this the same for everyone?

**Comment by ZhaoCancanCN** [comment]
Hi! I met the same error as you. Could you tell me how can i solve it?
Thank you!

**Comment by ZhaoCancanCN** [comment]
@ERGOWHO

**Comment by ERGOWHO** [comment]
> Hi! I met the same error as you. Could you tell me how can i solve it? Thank you!

Hi I think the author actually said this in the readme, just set
mesh_freq: 40
Then it works perfectly!

**Comment by ZhaoCancanCN** [comment]
![image](https://github.com/idiap/ESLAM/assets/82369784/5a80daca-23f3-4e94-8f7d-d939688eb368)


Thank you for your suggestion, but when I modify the mesh_ Freq: 40, the same issue still occurs, even adding message resolution according to the author's suggestion, which makes me puzzled. Here are the terminal output and ESLAM.yaml and replica.yaml files I ran. Can you give me some suggestions? Thank you.

For simplicity, I only ran 50 frames.
(eslam) :~/experiment/ESLAM$ python visualizer.py configs/Replica/room0.yaml --output output/Replica/room0 --top_view --save_rendering
Get ckpt : output/Replica/room0/ckpts/01999.tar
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:05<00:00,  9.90it/s]
ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, image2, from 'output/Replica/room0/tmp_rendering/*.jpg':
  Duration: 00:00:03.57, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1853x1025 [SAR 1:1 DAR 1853:1025], 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[swscaler @ 0x5604f978dae0] deprecated pixel format used, make sure you did set range correctly
[libx264 @ 0x5604f9361b40] using SAR=2292/2293
[libx264 @ 0x5604f9361b40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5604f9361b40] profile High, level 3.1
[libx264 @ 0x5604f9361b40] 264 - core 152 r2854 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=16 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'output/Replica/room0/vis.mp4':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuvj420p(pc), 926x512 [SAR 474368:474575 DAR 1853:1025], q=-1--1, 30 fps, 15360 tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.107.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=  107 fps=0.0 q=-1.0 Lsize=      36kB time=00:00:03.46 bitrate=  84.3kbits/s speed=6.16x    
video:34kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 6.180592%
[libx264 @ 0x5604f9361b40] frame I:1     Avg QP: 7.85  size:  1375
[libx264 @ 0x5604f9361b40] frame P:27    Avg QP:16.91  size:   840
[libx264 @ 0x5604f9361b40] frame B:79    Avg QP:15.84  size:   122
[libx264 @ 0x5604f9361b40] consecutive B-frames:  0.9%  0.0%  5.6% 93.5%
[libx264 @ 0x5604f9361b40] mb I  I16..4: 99.1%  0.0%  0.9%
[libx264 @ 0x5604f9361b40] mb P  I16..4:  0.0%  0.0%  0.0%  P16..4:  0.6%  0.4%  0.2%  0.0%  0.0%    skip:98.7%
[libx264 @ 0x5604f9361b40] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  0.5%  0.1%  0.0%  direct: 0.0%  skip:99.4%  L0:47.2% L1:46.7% BI: 6.1%
[libx264 @ 0x5604f9361b40] 8x8 transform intra:1.2% inter:21.4%
[libx264 @ 0x5604f9361b40] coded y,uvDC,uvAC intra: 1.2% 2.8% 2.6% inter: 0.2% 0.4% 0.4%
[libx264 @ 0x5604f9361b40] i16 v,h,dc,p: 97%  0%  3%  0%
[libx264 @ 0x5604f9361b40] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 14%  0% 79%  5%  1%  0%  0%  0%  0%
[libx264 @ 0x5604f9361b40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 20% 22% 40%  5%  4%  3%  3%  3%  1%
[libx264 @ 0x5604f9361b40] i8c dc,h,v,p: 96%  2%  2%  0%
[libx264 @ 0x5604f9361b40] Weighted P-Frames: Y:74.1% UV:44.4%
[libx264 @ 0x5604f9361b40] ref P L0: 60.6%  4.8% 18.4%  9.9%  6.4%
[libx264 @ 0x5604f9361b40] ref B L0: 87.7%  7.8%  4.5%
[libx264 @ 0x5604f9361b40] ref B L1: 99.2%  0.8%
[libx264 @ 0x5604f9361b40] kb/s:75.61

ESLAM.yaml
scale: 1
verbose: False
device: "cuda:0"
keyframe_device: "cuda:0" ## Change this to "cpu" to reduce GPU memory usage
planes_res:
  coarse: 0.24
  fine: 0.06
  bound_dividable: 0.24
c_planes_res:
  coarse: 0.24
  fine: 0.03
meshing:
  level_set: 0
  resolution: 0.05 # Increase this number to speed up meshing algorithm
  eval_rec: False
  mesh_bound_scale: 1.02
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  vis_freq: 4000
  vis_inside_freq: 400
  const_speed_assumption: True
  no_vis_on_first_frame: True
  gt_camera: False
  lr_T: 0.001
  lr_R: 0.001
  pixels: 2000
  iters: 8
  w_sdf_fs: 10
  w_sdf_center: 200
  w_sdf_tail: 50
  w_depth: 1
  w_color: 5
mapping:
  every_frame: 4
  joint_opt: True
  joint_opt_cam_lr: 0.001
  no_vis_on_first_frame: True
  no_mesh_on_first_frame: True
  no_log_on_first_frame: True
  vis_freq: 4000
  vis_inside_freq: 400 #each iteration
  mesh_freq: 40 #4000
  ckpt_freq: 500
  keyframe_every: 4
  mapping_window_size: 20
  keyframe_selection_method: 'overlap'
  lr_first_factor: 5
  lr_factor: 1
  pixels: 4000
  iters_first: 1000
  iters: 15
  w_sdf_fs: 5
  w_sdf_center: 200
  w_sdf_tail: 10
  w_depth: 0.1
  w_color: 5
  lr:
    decoders_lr: 0.001
    planes_lr: 0.005
    c_planes_lr: 0.005
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0
rendering:
  n_stratified: 32
  n_importance: 8
  perturb: True
  learnable_beta: True
model:
  c_dim: 32
  truncation: 0.06

replica.yaml
dataset: 'replica'
meshing:
  resolution: 0.05 # Increase this number to speed up meshing algorithm
  eval_rec: True
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  lr_T: 0.002
  lr_R: 0.001
  pixels: 2000
  iters: 8
mapping:
  pixels: 4000
  iters: 15
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0
rendering:
  n_stratified: 32
  n_importance: 8
  learnable_beta: True
