### ISSUE TITLE
output/tmp_rendering jpg frames are all black images with out showing the mesh background

### ISSUE THREAD

**Issue by ERGOWHO** [idiap/ESLAM#11]
Hi,

I can see the correct mesh+trajectory will run the visualizer.py, but when I check output/tmp_rendering the jpg frames are all black and vis.mp4 is also all black, do know why this is happening?

I also have this [mjpeg @ 0x5566f358ae00] EOI missing, emulating waring will running the visualizer.py

Thanks in advance.

**Comment by MohammadJohari** [comment]
Hello,

You need to lower `mesh_freq` to something like 40, and increase `meshing/resolution`
