### ISSUE TITLE
About bound and  marching_cubes_bound

### ISSUE THREAD

**Issue by bilibilijin** [idiap/ESLAM#13]
Hi，
Thank you for your excellent work。For the bound and marching in the configuration file_ Cubes_ I have some questions about bound and I need your help. May I ask what is the reason for setting it here? I think this is a hyperparameter. If I want to use my own dataset to run ESLAM, how should I configure bound and marching_ Cubes_bound。
Thanks in advance.

**Comment by MohammadJohari** [comment]
Hi,

Yes, that is a hyper parameters and you should set it in a way that it at least cover your whole room/apartment. You could provide the number in actual meter scale, or normalize them arbitrary. Just note that you should also set the camera pose of the first frame, and it should match the bounds that you give to the model. I mean, all other predicted camera poses are relative to the first camera pose, and the reconstructed mesh should fit in the bounds you define at the beginning.

Kind regards,
