### ISSUE TITLE
feature_planes value not changed during training

### ISSUE THREAD

**Issue by 00Haocheng** [idiap/ESLAM#14]
I understand from the thesis that feature_plane takes part in the training. But when I debugging,I find that  though the reconstruction result is good, the value of feature_plane seems to be not changed,.   Is there something wrong with my operation

**Comment by MohammadJohari** [comment]
Your understanding is correct. Note that feature_planes are only updated/optimized during the mapping step, and they are only used in read-only mode in tracking. Is it possible that for your debugging, you are examining the tracking part of the source code?
