### ISSUE TITLE
Novel View Render

### ISSUE THREAD

**Issue by zero-joke** [idiap/ESLAM#17]
![image](https://github.com/idiap/ESLAM/assets/65877841/2eb1c58c-1005-4cfb-b2f3-086cb54928a9)
Dose render a image mush be use gt_depth as arg? how can I render a image with Novel View?

**Comment by MohammadJohari** [comment]
You can pass all zero values for gt_depth and the function will operate assuming there are no depth values available. However, note that for training and optimization, our method heavily relies on depth values and cannot be trained properly without them.
