### ISSUE TITLE
Control random number seeds 

### ISSUE THREAD

**Issue by ZhaoCancanCN** [idiap/ESLAM#18]
Thank you for your wonderful work,

 and have you ever tried to control random number seeds to make the results reproducible? But I was trying to add random seeds and found that there was no guarantee that the output would be consistent every time. And I found that as long as the network performs a backpropagation, the output results at this time are already inconsistent. Do you know how to solve it? 

Thank you!

```
def setup_seed(seed):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
```

**Comment by MohammadJohari** [comment]
Hello,

Thank you very much for your interest in our work. Unfortunately, we did not try to force the initialization and optimization process to be deterministic. However, as evidenced in our experiments, our results are quite stable from run to run and we observe a small variance in localization and reconstruction accuracies.

Kind regards,
