### ISSUE TITLE
Mesh comparison: ReplicaViewer to check mesh

### ISSUE THREAD

**Issue by Dakai77777** [idiap/ESLAM#19]
Hallo,

thanks for your great job!
I want to compare different reconstructed mesh at same view for Replica Dataset. But actually, at Replica official website they provide the mesh without texture. They provide also ReplicaViewer to check rendered mesh. However, it is hard to adjust recontructed mesh in meshlab with ReplicaViewe.

 Is it possible to get textured mesh from  ReplicaViewer? How can you check them like Figure 3. in paper?  

I really appreciate any help you can provide!

Dakai

**Comment by MohammadJohari** [comment]
Hello,

Many thanks for your interest in our work. This was actually a problem that we were struggling with during our experiments, and we did not find a solution for it.

In the end, for qualitative comparison, we captured the rendered scene from ReplicaViewer from camera parameters that approximately was visually consistent with the meshes in MeshLab. In other words, we manually tuned the image-capturing position in ReplicaViewer with the MeshLab.

Kind regards,
