### ISSUE TITLE
Visualizaton Error

### ISSUE THREAD

**Issue by SharineLee** [idiap/ESLAM#8]
When I visualized the results of the dataset, the resulting view consisted only of the camera's trajectory and no scene mesh.

There is some warning when i run `python visualizer.py configs/Replica/room0.yaml --output output/Replica/room0 --top_view --save_rendering`:

`[mjpeg @ 0x562cad8edf00] overread 8 7424kB time=00:06:44.10 bitrate= 150.5kbits/s speed=3.91x
   [mjpeg @ 0x562cad8edf00] EOI missing, emulating`

**Comment by ERGOWHO** [comment]
![image](https://github.com/idiap/ESLAM/assets/69840908/6986c3a8-556c-409f-abf7-de8c81e515c9)
is this what you got? Same here.

I even do not have any errors or warnings.

**Comment by ERGOWHO** [comment]
Try to set the mesh_freq lower. It works on my side now.

**Comment by MohammadJohari** [comment]
Hello,

lowering mesh_freq would solve it. Increasing meshing/resolution will also speed up the reconstruction.
